setup: &setup
  http_observe?: true
  http_observe_url: 'http://localhost:8080/api/mail_messages'
  listen: '0.0.0.0'
  port: 2525
  log_level: debug
  pidfile: tmp/pids/mail_sandbox.pid

development:
  <<: *setup

production:
  <<: *setup

test:
  <<: *setup
