setup: &setup
  facebook:
    app_id: ''
    app_secret: ''
  github:
    app_id: ''
    app_secret: ''
  airbrake:
    api_key: ''
    host: ''

staging:
  <<: *setup

development:
  <<: *setup

production:
  <<: *setup

test:
  <<: *setup
